DELETE FROM wod_world.trinity_string
WHERE entry >= 100000;

-- Colors and color closure
SET @C_TITLE := '|cffd2691e';
SET @C_LINK := '|cffff4500';
SET @C_TEXT := '|cffbbbbbb';
SET @C_ERR := '|cffff0000';
SET @C_CLOSE := '|r'; -- stops/closes color tag

-- Templates
SET @T_CMD_INFO := CONCAT(@C_TITLE, '>> ', @C_CLOSE);
SET @T_CMD_SYNTAX := CONCAT(@C_TITLE, 'SYNTAX: ', @C_CLOSE);
SET @T_CMD_ERROR := CONCAT(@C_ERR, 'ERROR: ', @C_CLOSE);
SET @T_GLOBAL_GM := CONCAT(@C_LINK, '[GM-NOTIFY]', @C_CLOSE);

INSERT INTO wod_world.trinity_string (entry, content_default) VALUES
/* FREEDOM_CMDE_NOT_YET_IMPLEMENTED 					*/ (100000, CONCAT(@T_CMD_ERROR, @C_TEXT, 'This command isn\'t implemented yet.', @C_CLOSE)),
/* FREEDOM_CMDI_MONEY_RESET 								*/ (100001, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your money has been reset.', @C_CLOSE)),
/* FREEDOM_CMDE_NOT_ENOUGH_PARAMS 						*/ (100002, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Not enough parameters.', @C_CLOSE)),
/* FREEDOM_CMDH_GOTO_RELATIVE 							*/ (100003, CONCAT(@T_CMD_SYNTAX, '.goto $local_x [$local_y [$local_z [$local_deg]]]')),
/* FREEDOM_E_INVALID_MAP_COORD 							*/ (100004, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Target map or coordinates is invalid (X: %f Y: %f MapId: %u).', @C_CLOSE)),
/* FREEDOM_CMDI_FLAG_FOR_CUSTOMIZATION					*/ (100005, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your character has been successfully flagged for re-customization.', @C_CLOSE)),
/* FREEDOM_CMDI_FLAG_FOR_RACECHANGE						*/ (100006, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your character has been successfully flagged for race change.', @C_CLOSE)),
/* FREEDOM_CMDI_FLAG_FOR_FACTIONCHANGE					*/ (100007, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your character has been successfully flagged for faction change.', @C_CLOSE)),
/* FREEDOM_CMDI_FIX_ITEMS									*/ (100008, CONCAT(@T_CMD_INFO, @C_TEXT, 'All your character\'s items are repaired.', @C_CLOSE)),
/* FREEDOM_CMDH_WATERWALK 									*/ (100009, CONCAT(@T_CMD_SYNTAX, '.freedom waterwalk on/off')),
/* FREEDOM_CMDI_WATERWALK									*/ (100010, CONCAT(@T_CMD_INFO, @C_TEXT, 'Waterwalk toggle: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDH_DRUNK 										*/ (100011, CONCAT(@T_CMD_SYNTAX, '.freedom drunk $drunkPercentage ($drunkPercentage must be between 0 and 100)')),
/* FREEDOM_CMDI_DRUNK										*/ (100012, CONCAT(@T_CMD_INFO, @C_TEXT, 'Drunkenness level set to ', @C_LINK, '%d%%', @C_CLOSE)),
/* FREEDOM_CMDH_MOD_SPEED									*/ (100013, CONCAT(@T_CMD_SYNTAX, '.freedom swim/fly/walk/run/speed $speedValue')),
/* FREEDOM_CMDI_MOD_SPEED 									*/ (100014, CONCAT(@T_CMD_INFO, @C_TEXT, 'Movement speed of type ', @C_LINK, '%s', @C_TEXT, ' was set to value ', @C_LINK, '%.2f', @C_CLOSE)),
/* FREEDOM_CMDE_VALUE_OUT_OF_RANGE 						*/ (100015, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Given value was out of allowed range (Max: ', @C_LINK, '%.2f', @C_TEXT, ', Min: ', @C_LINK, '%.2f', @C_TEXT, ').', @C_CLOSE)),
/* FREEDOM_CMDH_FLY 											*/ (100016, CONCAT(@T_CMD_SYNTAX, '.freedom fly on/off')),
/* FREEDOM_CMDI_FLY											*/ (100017, CONCAT(@T_CMD_INFO, @C_TEXT, 'Fly toggle: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDI_DEMORPH 									*/ (100018, CONCAT(@T_CMD_INFO, @C_TEXT, 'You have been successfully demorphed.', @C_CLOSE)),
/* FREEDOM_CMDH_SCALE										*/ (100019, CONCAT(@T_CMD_SYNTAX, '.freedom scale $scaleValue')),
/* FREEDOM_CMDI_SCALE										*/ (100020, CONCAT(@T_CMD_INFO, @C_TEXT, 'You have been scaled to value ', @C_LINK, '%.2f', @C_CLOSE)),
/* FREEDOM_CMDI_UNAURA										*/ (100021, CONCAT(@T_CMD_INFO, @C_TEXT, 'All auras have been successfully removed from you.', @C_CLOSE)),
/* FREEDOM_CMDI_REVIVE										*/ (100022, CONCAT(@T_CMD_INFO, @C_TEXT, 'You have successfully crawled back from the dead.', @C_CLOSE)),
/* FREEDOM_CMDE_REVIVE 										*/ (100023, CONCAT(@T_CMD_ERROR, @C_TEXT, 'You are already alive.', @C_CLOSE)),
/* FREEDOM_CMDH_SUMMON										*/ (100024, CONCAT(@T_CMD_SYNTAX, '.freedom summon $playerName')),
/* FREEDOM_CMDI_SUMMON										*/ (100025, CONCAT(@T_CMD_INFO, @C_TEXT, 'Summon request sent to player ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_NOT_FOUND							*/ (100026, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'is either offline, currently loading or does not exist.', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_IGNORE								*/ (100027, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'is ignoring you.', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_GM_ON								*/ (100028, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'has GM tag ON.', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_EVIL_TWIN							*/ (100029, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'has Evil Twin aura. Summoning is not possible.', @C_CLOSE)),
/* FREEDOM_CMDI_RELOAD										*/ (100030, CONCAT(@T_GLOBAL_GM, @C_TEXT, ' Freedom DB table ', @C_LINK, '%s', @C_TEXT, ' has been reloaded.', @C_CLOSE)),
/* FREEDOM_CMDI_RELOAD_ALL									*/ (100031, CONCAT(@T_GLOBAL_GM, @C_TEXT, ' All freedom DB tables have been reloaded.', @C_CLOSE)),
/* FREEDOM_CMDI_SEARCH_QUERY_RESULT						*/ (100032, CONCAT(@T_CMD_INFO, @C_TEXT, 'Found total of ', @C_LINK, '%llu', @C_TEXT, ' result(s).', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_NAME_NOT_FOUND					*/ (100033, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with name ', @C_LINK, '%s', @C_TEXT, ' was not found.', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_ID_NOT_FOUND						*/ (100034, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with id ', @C_LINK, '%llu', @C_TEXT, ' was not found.', @C_CLOSE)),
/* FREEDOM_CMDI_X_NONE_FOUND_WITH_NAME					*/ (100035, CONCAT(@T_CMD_INFO, @C_TEXT, 'No %s with name part ', @C_LINK, '%s', @C_TEXT, ' were found.', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_NAME_ALREADY_EXISTS			*/ (100036, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with name ', @C_LINK, '%s', @C_TEXT, ' already exists.', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_ID_ALREADY_EXISTS				*/ (100037, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with id ', @C_LINK, '%llu', @C_TEXT, ' already exists.', @C_CLOSE)),
/* FREEDOM_CMDI_X_ADDED_WITH_NAME						*/ (100038, CONCAT(@T_CMD_INFO, @C_TEXT, '%s successfully added with following name: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDI_X_WITH_NAME_REMOVED						*/ (100039, CONCAT(@T_CMD_INFO, @C_TEXT, '%s with name ', @C_LINK, '%s', @C_TEXT, ' successfully removed.', @C_CLOSE)),
/* FREEDOM_CMDH_PUBLIC_TELE								*/ (100040, CONCAT(@T_CMD_SYNTAX, '.freedom teleport $namePart')),
/* FREEDOM_CMDH_PUBLIC_TELE_LIST							*/ (100041, CONCAT(@T_CMD_SYNTAX, '.freedom teleport list $namePart')),
/* FREEDOM_CMDI_PUBLIC_TELE_LIST_ITEM					*/ (100042, CONCAT(@T_CMD_INFO, @C_LINK, '%s', @C_TEXT, ' (Map: ', @C_LINK, '%s', @C_TEXT, ')', @C_CLOSE)),
/* FREEDOM_CMDH_PUBLIC_TELE_ADD							*/ (100043, CONCAT(@T_CMD_SYNTAX, '.freedom teleport add $name')),
/* FREEDOM_CMDH_PUBLIC_TELE_DEL							*/ (100044, CONCAT(@T_CMD_SYNTAX, '.freedom teleport delete $name')),
/* FREEDOM_CMDH_PRIVATE_TELE								*/ (100045, CONCAT(@T_CMD_SYNTAX, '.freedom pteleport $namePart')),
/* FREEDOM_CMDH_PRIVATE_TELE_LIST						*/ (100046, CONCAT(@T_CMD_SYNTAX, '.freedom pteleport list $namePart')),
/* FREEDOM_CMDI_PRIVATE_TELE_LIST_ITEM					*/ (100047, CONCAT(@T_CMD_INFO, @C_LINK, '%s', @C_TEXT, ' (Map: ', @C_LINK, '%s', @C_TEXT, ')', @C_CLOSE)),
/* FREEDOM_CMDH_PRIVATE_TELE_ADD							*/ (100048, CONCAT(@T_CMD_SYNTAX, '.freedom pteleport add $name')),
/* FREEDOM_CMDH_PRIVATE_TELE_DEL							*/ (100049, CONCAT(@T_CMD_SYNTAX, '.freedom pteleport delete $name')),
/* FREEDOM_CMDH_PUBLIC_SPELL								*/ (100050, CONCAT(@T_CMD_SYNTAX, '.freedom spell/cast $spellId/$spellLink')),
/* FREEDOM_CMDH_PUBLIC_SPELL_LIST						*/ (100051, CONCAT(@T_CMD_SYNTAX, '.freedom spell list $namePart')),
/* FREEDOM_CMDI_PUBLIC_SPELL_LIST_ITEM					*/ (100052, CONCAT(@T_CMD_INFO, @C_LINK, '%u', @C_TEXT, ' - %s', @C_CLOSE)),
/* FREEDOM_CMDH_PUBLIC_SPELL_ADD							*/ (100053, CONCAT(@T_CMD_SYNTAX, '.freedom spell add $spellId/$spellLink [true/false (true: allow spell to target others, false: spell only targets caster, by default: false)]')),
/* FREEDOM_CMDH_PUBLIC_SPELL_DEL							*/ (100054, CONCAT(@T_CMD_SYNTAX, '.freedom spell delete $spellId/$spellLink')),
/* FREEDOM_CMDH_MORPH										*/ (100055, CONCAT(@T_CMD_SYNTAX, '.freedom morph $name/$displayId')),
/* FREEDOM_CMDH_MORPH_LIST									*/ (100056, CONCAT(@T_CMD_SYNTAX, '.freedom morph list [$namePart]')),
/* FREEDOM_CMDI_MORPH_LIST_ITEM							*/ (100057, CONCAT(@T_CMD_INFO, @C_LINK, '%u', @C_TEXT, ' - ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDH_MORPH_ADD									*/ (100058, CONCAT(@T_CMD_SYNTAX, '.freedom morph add $name $displayId [$playerName (if not supplied, then add morph to selected player)]')),
/* FREEDOM_CMDH_MORPH_DEL									*/ (100059, CONCAT(@T_CMD_SYNTAX, '.freedom morph delete $name/$displayId [$playerName (if not supplied, then add morph to selected player)]')),
/* FREEDOM_CMDE_INVALID_SELECTION 						*/ (100060, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Invalid selection.', @C_CLOSE)),
/* FREEDOM_CMDI_X_NOT_FOUND								*/ (100061, CONCAT(@T_CMD_INFO, @C_TEXT, '%s not found.', @C_CLOSE)),
/* FREEDOM_CMDE_INVALID_ARGUMENT_X						*/ (100062, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Invalid argument for: ', @C_CLOSE, '%s')),
/* FREEDOM_CMDI_MORPH										*/ (100063, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your model display was set to following morph: ', @C_LINK, '%s', @C_TEXT, ' (Display ID: ', @C_LINK, '%u', @C_TEXT, ')', @C_CLOSE)),
/* FREEDOM_CMDI_MORPH_ADD									*/ (100064, CONCAT(@T_CMD_INFO, @C_TEXT, 'Morph (Name: ', @C_LINK, '%s', @C_TEXT, ', Display ID: ', @C_LINK, '%u', @C_TEXT, ') successfully added to following player: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDI_MORPH_DEL									*/ (100065, CONCAT(@T_CMD_INFO, @C_TEXT, 'Morph (Name: ', @C_LINK, '%s', @C_TEXT, ', Display ID: ', @C_LINK, '%u', @C_TEXT, ') successfully removed from following player: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDI_PUBLIC_SPELL_ADD							*/ (100066, CONCAT(@T_CMD_INFO, @C_TEXT, 'Public spell (Name link: %s, Spell ID: ', @C_LINK, '%u', @C_TEXT, ') successfully added to public spell list.', @C_CLOSE)),
/* FREEDOM_CMDI_PUBLIC_SPELL_DEL							*/ (100067, CONCAT(@T_CMD_INFO, @C_TEXT, 'Public spell (Name link: %s, Spell ID: ', @C_LINK, '%u', @C_TEXT, ') successfully removed from public spell list.', @C_CLOSE)),
/* FREEDOM_CMDH_HOVER 										*/ (100068, CONCAT(@T_CMD_SYNTAX, '.freedom hover on/off')),
/* FREEDOM_CMDI_HOVER										*/ (100069, CONCAT(@T_CMD_INFO, @C_TEXT, 'Hover toggle: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_PENDING							*/ (100070, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'already has a pending summon request from someone.', @C_CLOSE)),
/* FREEDOM_CMDE_X_IS_BLACKLISTED							*/ (100071, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s is blacklisted. Only GMs or higher can bypass this.', @C_CLOSE)),
/* FREEDOM_CMDH_BLACKLIST_ITEM							*/ (100072, CONCAT(@T_CMD_SYNTAX, '.blacklist item $itemId/$itemLink [$flag] ($flag = 1 by default)')),
/* FREEDOM_CMDI_BLACKLIST_ITEM							*/ (100073, CONCAT(@T_CMD_INFO, 'Item successfully ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDNOSTYLE_ID_AND_NAME_LIST_ITEM			*/ (100074, '%u - %s'),
/* FREEDOM_CMDI_ID_AND_NAME_LIST_ITEM_BLACKLISTED  */ (100075, CONCAT('%u - %s ', @C_ERR, 'BLACKLISTED', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_GUID_NOT_FOUND					*/ (100076, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with guid ', @C_LINK, '%llu', @C_TEXT, ' was not found.', @C_CLOSE)),
/* FREEDOM_CMDE_GAMEOBJECT_SELECT_ENTRY_ID			*/ (100077, CONCAT(@T_CMD_ERROR, 'Cannot find gameobject template (Entry ID: %u) for selected game object with guid %llu. Contact developers about this!')),
/* FREEDOM_CMDE_GAMEOBJECT_SELECT_NOT_IN_WORLD		*/ (100078, CONCAT(@T_CMD_ERROR, 'Cannot find gameobject object instance for selected gameobject with guid %llu (Entry ID: %u). Contact developers about this!')),
/* FREEDOM_CMDI_GAMEOBJECT_SELECT						*/ (100079, CONCAT(@T_CMD_INFO, 'Selected gameobject %s (GUID: %llu, Entry ID: %u, Distance: %.3f yards)')),
/* FREEDOM_CMDI_GAMEOBJECT_ACTIVATED 					*/ (100080, CONCAT(@T_CMD_INFO, 'Gameobject %s activated!')),
/* FREEDOM_CMDE_TEMPLATE_DOES_NOT_EXIST				*/ (100081, CONCAT(@T_CMD_ERROR, 'Template (GUID: %llu, Entry ID: %u) cannot be found. Contact developers about this!')),
/* FREEDOM_CMDH_GAMEOBJECT_SPAWN							*/ (100082, CONCAT(@T_CMD_SYNTAX, '.gobject add/spawn [temp] $entryId [$spawnTimeSecs]')),
/* FREEDOM_CMDE_GAMEOBJECT_SPAWN_INVALID_ID			*/ (100083, CONCAT(@T_CMD_ERROR, 'Invalid gameobject entry ID')),
/* FREEDOM_CMDE_GAMEOBJECT_SPAWN_FAIL					*/ (100084, CONCAT(@T_CMD_ERROR, 'Failed to spawn gameobject with entry %u (Invalid data, db fail or instance creation fail).')),
/* FREEDOM_CMDI_GAMEOBJECT_SPAWN							*/ (100085, CONCAT(@T_CMD_INFO, 'Gameobject %s spawned (GUID: %llu, Entry ID: %u)')),
/* FREEDOM_CMDE_GAMEOBJECT_SPAWN_INVALID_DISPLAY	*/ (100086, CONCAT(@T_CMD_ERROR, 'Failed to spawn gameobject with entry %u (Invalid display: cannot find display with id %u). Contact developers about this!')),
/* FREEDOM_CMDI_GAMEOBJECT_NEAR							*/ (100087, CONCAT(@T_CMD_INFO, 'Found %u gameobjects in %.3f yards.')),
/* FREEDOM_CMDI_GAMEOBJECT_NEAR_MAX_RESULT_COUNT	*/ (100088, CONCAT(@T_CMD_INFO, 'Found %u (Max result count) gameobjects in %.3f yards.')),
/* FREEDOM_CMDE_GAMEOBJECT_GUID_NOT_EXISTS			*/ (100089, CONCAT(@T_CMD_ERROR, 'Gameobject with GUID %llu does not exist!')),
/* FREEDOM_CMDE_GAMEOBJECT_ENTRY_NOT_EXISTS			*/ (100090, CONCAT(@T_CMD_ERROR, 'Gameobject with entry %u does not exist!')),
/* FREEDOM_CMDI_GAMEOBJECT_NEAR_LIST_ITEM				*/ (100091, '%.3f yards - Entry: %u : %s'),
/* FREEDOM_CMDI_GAMEOBJECT_MOVE							*/ (100092, CONCAT(@T_CMD_INFO, 'Gameobject %s (GUID: %llu) moved')),
/* FREEDOM_CMDE_INVALID_TARGET_COORDS					*/ (100093, CONCAT(@T_CMD_ERROR, 'Invalid target coordinates (X: %.4f, Y: %.4f, Z: %.4f, MapID: %u)')),
/* FREEDOM_CMDE_GAMEOBJECT_NOT_FOUND					*/ (100094, CONCAT(@T_CMD_ERROR, 'Gameobject not found!')),
/* FREEDOM_CMDI_GAMEOBJECT_TURNED						*/ (100095, CONCAT(@T_CMD_INFO, 'Gameobject %s (GUID: %llu) turned')),
/* FREEDOM_CMDI_GAMEOBJECT_DELETE						*/ (100096, CONCAT(@T_CMD_INFO, 'Gameobject deleted')),
/* FREEDOM_CMDI_GAMEOBJECT_SET_STATE					*/ (100097, CONCAT(@T_CMD_INFO, 'Gameobject state/type set (Type: %u, State: %u)')),
/* FREEDOM_CMDH_GAMEOBJECT_SET_STATE					*/ (100098, CONCAT(@T_CMD_SYNTAX, '.gobject set state $type $state [$guid]')),
/* FREEDOM_CMDH_GAMEOBJECT_SCALE							*/ (100099, CONCAT(@T_CMD_SYNTAX, '.gobject scale $scale [$guid]')),
/* FREEDOM_CMDI_GAMEOBJECT_SCALE							*/ (100100, CONCAT(@T_CMD_INFO, 'Gameobject scale set to %.5f')),
/* FREEDOM_CMDI_GAMEOBJECT_INFO							*/ (100101, CONCAT(@T_CMD_INFO, 'Gameobject %s information:')),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_GUID_FULL			*/ (100102, '> GUID (full): %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_GUID				*/ (100103, '> GUID: %llu'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_ENTRY				*/ (100104, '> Entry ID: %u %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_DISPLAY_ID		*/ (100105, '> Display ID: %u'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_SCRIPT_ID			*/ (100106, '> Script ID: %u'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_NAME				*/ (100107, '> Name: %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_AI_NAME			*/ (100108, '> AIName: %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_PHASEMASK			*/ (100109, '> PhaseMask: %u'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_PHASELIST			*/ (100110, '> Active phase list (PhaseID - PhaseMask):'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_PHASE_LI			*/ (100111, '\t* %u - %u'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_POS_X				*/ (100112, '> X: %.4f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_POS_Y				*/ (100113, '> Y: %.4f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_POS_Z				*/ (100114, '> Z: %.4f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_ORIENTATION		*/ (100115, '> Orientation: %.4f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_DISTANCE			*/ (100116, '> Distance: %.3f yards'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_SCALE				*/ (100117, '> Scale: %.5f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_STATE				*/ (100118, '> State: (%u) %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_CREATOR_PLAYER	*/ (100119, '> Creator player: %s (ID: %llu)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_CREATOR_ACC		*/ (100120, '> Creator account: %s (BnetID: %u)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_MODIFIER_PLAYER	*/ (100121, '> Modifier player: %s (ID: %llu)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_MODIFIER_ACC		*/ (100122, '> Modifier account: %s (BnetID: %u)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_CREATED			*/ (100123, '> Created: %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_MODIFIED			*/ (100124, '> Modified: %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_NO_HISTORY		*/ (100125, '> [History unavailable/not found]'),


(200000, 'Dummy');
-- Select new changes
SELECT * FROM wod_world.trinity_string
WHERE entry >= 100000;